# Generated by Django 5.2.4 on 2025-08-31 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0002_alter_voter_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='username',
        ),
    ]
