# Generated by Django 5.2.4 on 2025-08-31 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0003_remove_voter_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='election',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'candidate')},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='election',
        ),
        migrations.DeleteModel(
            name='Election',
        ),
    ]
