# Generated by Django 5.2.4 on 2025-08-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0004_remove_candidate_election_alter_vote_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
