# Generated by Django 5.2.4 on 2025-09-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elections', '0005_alter_candidate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='manifesto',
            field=models.TextField(default=1000, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
